name: Build RE2 Non-RT Upscaler

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-re2-tdb66:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Check Build Tools
        shell: pwsh
        run: |
          Write-Host "Checking compiler..."
          cl
          Write-Host "Checking Ninja..."
          ninja --version
          Write-Host "Checking CMake..."
          cmake --version

      - name: Configure CMake
        run: >
          cmake
          -S ${{ github.workspace }}
          -B ${{ github.workspace }}/build
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DDEVELOPER_MODE=ON
          "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

      - name: Build RE2_TDB66
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config ${{ env.BUILD_TYPE }}
          --target RE2_TDB66
          --parallel

      - name: Package
        shell: pwsh
        run: |
          echo "${{ github.sha }}" > reframework_revision.txt
          echo "none" > DELETE_OPENVR_API_DLL_IF_YOU_WANT_TO_USE_OPENXR

          7z a RE2_TDB66.zip reframework_revision.txt
          7z a RE2_TDB66.zip DELETE_OPENVR_API_DLL_IF_YOU_WANT_TO_USE_OPENXR
          7z a RE2_TDB66.zip build/bin/RE2_TDB66/dinput8.dll
          7z a RE2_TDB66.zip dependencies/openvr/bin/win64/openvr_api.dll
          7z a RE2_TDB66.zip build/_deps/openxr-build/src/loader/${{ env.BUILD_TYPE }}/openxr_loader.dll
          7z a RE2_TDB66.zip scripts
          7z rn RE2_TDB66.zip scripts reframework/autorun

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RE2_TDB66
          path: RE2_TDB66.zip
          if-no-files-found: error
